"""Multiresolution Resonance Network public API."""

from .attention import AttentionCandidates, DotProductCandidateAttention, ResonantAttention
from .abstraction_control import (
    AbstractionApplicability, AbstractionApplicabilityHead,
    AbstractionLevelSelector, AbstractionRevisionProposal,
    AbstractionSelection, AbstractionValidityState,
    LocalizedDescentPlan, LocalizedDescentPlanner,
)
from .action_candidates import (
    ActionCandidateState, authorize_candidate_provenance,
    build_action_candidates, evaluate_candidate_rollout, select_action_candidate,
)
from .agent_session import (
    CognitiveAgentSession, DeliberationResult, ExecutionReceipt,
    ExecutorResult, SessionStepResult, StructuredEnvironmentExecutor,
)
from .boundaries import BoundaryContextState, legacy_scope
from .checkpoint import load_stream_checkpoint, save_stream_checkpoint
from .config import CognitiveConfig, MRCRAConfig, MRRNConfig, ScaleConfig
from .cognitive_checkpoint import load_mrcra_checkpoint, save_mrcra_checkpoint
from .cognitive_diagnostics import cognitive_evidence, cognitive_metrics
from .cognitive_model import (
    ActionStatus, CognitiveActionReceipts, MRCRAOutput, MRCRARuntimeState,
    MRCRAStepOutput, MultimodalRelationalContinuityResonanceNetwork,
)
from .cognitive_objectives import (
    CognitiveLossBreakdown, CognitiveObjectiveSchedule, MetacognitiveTargets,
    ObjectiveFamily, ObjectiveTerm, combine_cognitive_objectives,
    metacognitive_objectives,
)
from .cognitive_surprise import (
    CognitiveAdjointCritic, CognitiveRASLConfig, CognitiveRASLStepReport,
    CognitiveReplaySample, CognitiveResonantAdjointSurpriseLearner,
    CognitiveTrajectoryBatch, CognitiveTrajectoryReplay,
    build_language_candidate_set, load_cognitive_rasl_checkpoint,
    save_cognitive_rasl_checkpoint,
)
from .cognitive_training import (
    CognitiveSupervisionProvider, MRCRANextTokenTrainer, MRCRATrainingConfig,
    MRCRATrainingState, TiledCrossEntropy, exact_tiled_cross_entropy,
)
from .empirical_acceptance import (
    BENCHMARKS, EmpiricalAcceptanceReport, EmpiricalBenchmarkResult,
    EmpiricalCriterion, benchmark_consequence_learning, benchmark_continual_adaptation,
    benchmark_controller, benchmark_hierarchy, benchmark_multimodal_binding,
    benchmark_retrieval, benchmark_uncertainty, benchmark_world_model,
    run_empirical_acceptance,
)
from .cognitive_supervision import (
    CognitiveSupervisionTargets, CognitiveTargetResolver,
    EvidenceBackedCognitiveSupervisor, language_evidence_targets,
)
from .cognitive_types import (
    AgentMode, BoundaryClass, BoundaryScope, CognitiveClocks, CognitiveTrigger,
    InternalAction, ModalityClass, NodeType, RelationFamily, SourceClass,
    VerificationClass,
)
from .continual_adaptation import (
    AdaptationReceipt, ContinualReplayBuffer, IsolatedContinualAdapter,
    ReplayItem,
)
from .evidence_requests import (
    EvidenceRequestState, EvidenceRequestStatus, create_evidence_request,
    transition_evidence_requests,
)
from .external_artifacts import (
    ExternalArtifactState, record_external_artifact, verify_external_artifact,
)
from .gradient_governance import (
    GradientGovernanceReport, objective_gradient_report,
    project_conflicting_gradients,
)
from .lifting import LiftingAnalysisBank, LiftingStreamState, ReconstructionContext, ScaleTensor
from .interaction import (
    ActionParameterSpec, ActionSchema, ActionSchemaRegistry,
    EnvironmentExecutor, ExternalActionDecision, ExternalActionFeedback,
    ExternalActionPolicy, StructuredExternalAction, authorize_external_actions,
    execute_authorized_actions, update_system_model_from_feedback,
)
from .integrated_acceptance import (
    IntegratedAblationResult, IntegratedAcceptanceReport,
    run_integrated_acceptance,
)
from .knowledge import (
    KnowledgeKind, KnowledgeProposalBank, KnowledgeProposalBatch,
    KnowledgeProposalState, KnowledgeStatus, KnowledgeValidationBatch,
    KnowledgeValidationResult,
)
from .memory import EideticMemory, MemoryItem, MemoryWritePolicy
from .metacognition import (
    MetacognitivePrediction, MetacognitiveRouter, MetacognitiveState,
    append_metacognitive_record,
)
from .mlx_backend import MLXCausalTransformer, MLXMRRN, mlx_available
from .mixer import HybridSpectralMixer, ResonantSpectralGLU
from .model import MRRN, MRRNOutput, MRRNState, MRRNStreamState
from .multimodal_io import MultimodalPacketAssembler, PreparedModality
from .language import (
    LanguageModelOutput,
    MRCRAGenerationOutput,
    MRCRALanguageModel,
    MRCRALanguageOutput,
    MRRNLanguageModel,
    fineweb_4p7m_config,
    fineweb_27m_config,
    tiny_language_config,
)
from .resonance import ComplexResonator, ResonatorState
from .observation import ObservationPacket, register_external_observations, register_internal_inputs
from .provenance import ProvenanceLedger, ProvenanceRecord, VerificationEvent
from .performance_acceptance import (
    PerformanceAcceptanceReport, PerformanceGateResult,
    run_performance_acceptance,
)
from .serious_acceptance import (
    REQUIRED_HELD_OUT_TASKS, SeriousCheckpointAcceptanceReport,
    SeriousCriterion, SeriousGate, SeriousPerformanceEvidence,
    SeriousTaskEvidence, audit_serious_checkpoint,
    build_serious_evaluation_artifact,
)
from .reconstruction import (
    ConditionalGraphReconstructor, ReconstructionEvidence, ReconstructionProposal,
    ReconstructionQuery, ReconstructionResult, ReconstructionState,
)
from .surprise import (
    AdjointCriticOutput,
    ActorLossBreakdown,
    CriticLossBreakdown,
    FunctionalSurpriseCalibrator,
    FunctionalSurpriseTarget,
    PerformanceGuard,
    PrioritizedTrajectoryReplay,
    RASLLosses,
    RASLParameterReport,
    RASLStepReport,
    ResonantAdjointCritic,
    ResonantAdjointSurpriseConfig,
    ResonantAdjointSurpriseLearner,
    TrajectoryBatch,
    actor_losses,
    critic_losses,
    functional_surprise_target,
    multihorizon_returns,
    phase_aware_latent_error,
    quantile_huber_loss,
    load_rasl_checkpoint,
    save_rasl_checkpoint,
)
from .hypotheses import RoutedHypotheses
from .training_profiles import (
    TrainerMode, TrainingAuthorityReport, TrainingProfile, get_training_profile,
    validate_training_authority,
)
from .viability import (
    CandidateViabilityForecaster, ViabilityDecision, ViabilityForecast,
    ViabilityGate, ViabilityState, update_measured_viability,
)
from .world_model import CandidateRollout

__all__ = [
    "AttentionCandidates",
    "AbstractionApplicability",
    "AbstractionApplicabilityHead",
    "AbstractionLevelSelector",
    "AbstractionRevisionProposal",
    "AbstractionSelection",
    "AbstractionValidityState",
    "ActionCandidateState",
    "CandidateRollout",
    "CandidateViabilityForecaster",
    "ActionParameterSpec",
    "ActionSchema",
    "ActionSchemaRegistry",
    "AdjointCriticOutput",
    "ActorLossBreakdown",
    "ActionStatus",
    "AdaptationReceipt",
    "AgentMode",
    "BoundaryClass",
    "BoundaryContextState",
    "BoundaryScope",
    "CognitiveActionReceipts",
    "CognitiveAgentSession",
    "CognitiveAdjointCritic",
    "CognitiveClocks",
    "CognitiveTrigger",
    "CognitiveConfig",
    "CognitiveObjectiveSchedule",
    "CognitiveRASLConfig",
    "CognitiveRASLStepReport",
    "CognitiveReplaySample",
    "CognitiveResonantAdjointSurpriseLearner",
    "CognitiveSupervisionProvider",
    "CognitiveSupervisionTargets",
    "CognitiveTargetResolver",
    "CognitiveTrajectoryBatch",
    "CognitiveTrajectoryReplay",
    "CognitiveLossBreakdown",
    "ComplexResonator",
    "ContinualReplayBuffer",
    "CriticLossBreakdown",
    "DotProductCandidateAttention",
    "DeliberationResult",
    "EideticMemory",
    "EnvironmentExecutor",
    "EvidenceBackedCognitiveSupervisor",
    "EvidenceRequestState",
    "EvidenceRequestStatus",
    "EmpiricalAcceptanceReport",
    "EmpiricalBenchmarkResult",
    "EmpiricalCriterion",
    "ExternalActionDecision",
    "ExternalActionFeedback",
    "ExternalActionPolicy",
    "ExternalArtifactState",
    "ExecutionReceipt",
    "ExecutorResult",
    "LiftingAnalysisBank",
    "LocalizedDescentPlan",
    "LocalizedDescentPlanner",
    "LiftingStreamState",
    "HybridSpectralMixer",
    "FunctionalSurpriseCalibrator",
    "FunctionalSurpriseTarget",
    "GradientGovernanceReport",
    "MRRN",
    "MRCRAConfig",
    "MRCRAGenerationOutput",
    "MRCRALanguageModel",
    "MRCRALanguageOutput",
    "MRCRANextTokenTrainer",
    "MRCRAOutput",
    "MRCRARuntimeState",
    "MRCRAStepOutput",
    "MRCRATrainingConfig",
    "MRCRATrainingState",
    "MRRNLanguageModel",
    "MRRNConfig",
    "MRRNOutput",
    "MRRNState",
    "MRRNStreamState",
    "LanguageModelOutput",
    "KnowledgeKind",
    "KnowledgeProposalBank",
    "KnowledgeProposalBatch",
    "KnowledgeProposalState",
    "KnowledgeStatus",
    "KnowledgeValidationBatch",
    "KnowledgeValidationResult",
    "MemoryItem",
    "MemoryWritePolicy",
    "MetacognitiveState",
    "MetacognitivePrediction",
    "MetacognitiveRouter",
    "MetacognitiveTargets",
    "ModalityClass",
    "MultimodalPacketAssembler",
    "MultimodalRelationalContinuityResonanceNetwork",
    "MLXCausalTransformer",
    "MLXMRRN",
    "ReconstructionContext",
    "ConditionalGraphReconstructor",
    "ReconstructionEvidence",
    "ReconstructionProposal",
    "ReconstructionQuery",
    "ReconstructionResult",
    "ReconstructionState",
    "ReplayItem",
    "InternalAction",
    "IntegratedAblationResult",
    "IntegratedAcceptanceReport",
    "IsolatedContinualAdapter",
    "NodeType",
    "ObservationPacket",
    "ObjectiveFamily",
    "ObjectiveTerm",
    "PerformanceAcceptanceReport",
    "PerformanceGateResult",
    "PerformanceGuard",
    "PreparedModality",
    "PrioritizedTrajectoryReplay",
    "RASLLosses",
    "RASLParameterReport",
    "RASLStepReport",
    "ResonantAdjointCritic",
    "ResonantAdjointSurpriseConfig",
    "ResonantAdjointSurpriseLearner",
    "ResonantAttention",
    "ResonantSpectralGLU",
    "ResonatorState",
    "RelationFamily",
    "RoutedHypotheses",
    "ScaleConfig",
    "ScaleTensor",
    "SeriousCheckpointAcceptanceReport",
    "SeriousGate",
    "SessionStepResult",
    "TrajectoryBatch",
    "TiledCrossEntropy",
    "TrainerMode",
    "TrainingAuthorityReport",
    "TrainingProfile",
    "ProvenanceLedger",
    "ProvenanceRecord",
    "SourceClass",
    "StructuredEnvironmentExecutor",
    "StructuredExternalAction",
    "VerificationClass",
    "ViabilityState",
    "ViabilityDecision",
    "ViabilityForecast",
    "ViabilityGate",
    "VerificationEvent",
    "actor_losses",
    "BENCHMARKS",
    "authorize_external_actions",
    "authorize_candidate_provenance",
    "append_metacognitive_record",
    "build_action_candidates",
    "benchmark_consequence_learning",
    "benchmark_continual_adaptation",
    "benchmark_controller",
    "benchmark_hierarchy",
    "benchmark_multimodal_binding",
    "benchmark_retrieval",
    "benchmark_uncertainty",
    "benchmark_world_model",
    "critic_losses",
    "cognitive_evidence",
    "cognitive_metrics",
    "combine_cognitive_objectives",
    "build_language_candidate_set",
    "exact_tiled_cross_entropy",
    "execute_authorized_actions",
    "evaluate_candidate_rollout",
    "functional_surprise_target",
    "fineweb_4p7m_config",
    "fineweb_27m_config",
    "load_stream_checkpoint",
    "load_mrcra_checkpoint",
    "load_cognitive_rasl_checkpoint",
    "load_rasl_checkpoint",
    "language_evidence_targets",
    "get_training_profile",
    "mlx_available",
    "metacognitive_objectives",
    "multihorizon_returns",
    "objective_gradient_report",
    "phase_aware_latent_error",
    "quantile_huber_loss",
    "project_conflicting_gradients",
    "save_rasl_checkpoint",
    "save_mrcra_checkpoint",
    "save_cognitive_rasl_checkpoint",
    "save_stream_checkpoint",
    "register_external_observations",
    "register_internal_inputs",
    "record_external_artifact",
    "run_empirical_acceptance",
    "run_integrated_acceptance",
    "run_performance_acceptance",
    "audit_serious_checkpoint",
    "build_serious_evaluation_artifact",
    "REQUIRED_HELD_OUT_TASKS",
    "SeriousCheckpointAcceptanceReport",
    "SeriousCriterion",
    "SeriousGate",
    "SeriousPerformanceEvidence",
    "SeriousTaskEvidence",
    "tiny_language_config",
    "create_evidence_request",
    "select_action_candidate",
    "transition_evidence_requests",
    "update_measured_viability",
    "update_system_model_from_feedback",
    "validate_training_authority",
    "verify_external_artifact",
    "legacy_scope",
]

__version__ = "4.0.0"
